# GitHub Sponsors configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Supported platforms:
# github: [fabioc-aloha]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# custom: ["https://www.example.com", "https://www.example.com"]

# Uncomment and configure when sponsorship is available
# github: [fabioc-aloha]
