/**
 * setupMarkdownCss.ts - Markdown preview CSS management
 *
 * Handles copying and applying GitHub-flavored markdown CSS
 * to the workspace for VS Code markdown preview.
 */

import * as vscode from 'vscode';
import * as path from 'path';

// Module-level variable to store extension path for CSS lookup
let cachedExtensionPath: string | undefined;

/**
 * Set the extension path for CSS file lookup.
 * Called during extension activation or from initialize command.
 */
export function setExtensionPathForCss(extensionPath: string): void {
  cachedExtensionPath = extensionPath;
}

/**
 * Copy the markdown preview CSS file to the workspace .vscode folder
 * 
 * VS Code has security restrictions that prevent loading CSS from arbitrary paths.
 * We must copy the CSS to each workspace's .vscode/ folder and use a relative path.
 * 
 * Priority order for CSS source:
 * 1. Workspace's .github/config/markdown-light.css (primary - after Alex initialize)
 * 2. Extension's bundled .github/config/markdown-light.css (bundled location)
 * 3. Legacy locations as fallback
 * 4. Embedded fallback CSS (last resort)
 */
async function copyMarkdownCssToWorkspace(): Promise<boolean> {
  const workspaceFolders = vscode.workspace.workspaceFolders;
  if (!workspaceFolders || workspaceFolders.length === 0) {
    console.error("No workspace folder open");
    return false;
  }

  const workspaceRoot = workspaceFolders[0].uri;
  const vscodeFolder = vscode.Uri.joinPath(workspaceRoot, ".vscode");
  const targetCssUri = vscode.Uri.joinPath(vscodeFolder, "markdown-light.css");

  let cssContent: Uint8Array | null = null;

  // Priority 1: Try workspace's .github/config/ (primary location after initialization)
  const githubConfigCss = vscode.Uri.joinPath(
    workspaceRoot,
    ".github",
    "config",
    "markdown-light.css"
  );

  try {
    cssContent = await vscode.workspace.fs.readFile(githubConfigCss);
  } catch {
    // CSS not found in workspace config folder
  }

  // Priority 2: Try extension's bundled .github/config folder (primary location)
  if (!cssContent && cachedExtensionPath) {
    const extensionConfigCss = vscode.Uri.file(
      path.join(cachedExtensionPath, ".github", "config", "markdown-light.css")
    );
    try {
      cssContent = await vscode.workspace.fs.readFile(extensionConfigCss);
    } catch {
      // CSS not found in extension config folder
    }
  }

  // Priority 3: Try legacy locations (skills folder, .vscode folder)
  if (!cssContent && cachedExtensionPath) {
    const legacyLocations = [
      path.join(cachedExtensionPath, ".vscode", "markdown-light.css"),
      path.join(cachedExtensionPath, ".github", "skills", "markdown-mermaid", "markdown-light.css")
    ];
    for (const location of legacyLocations) {
      try {
        cssContent = await vscode.workspace.fs.readFile(vscode.Uri.file(location));
        break;
      } catch {
        // Try next location
      }
    }
  }
  
  if (!cssContent && !cachedExtensionPath) {
    console.error("No cachedExtensionPath set, cannot read CSS from extension bundle");
  }

  // If not found in workspace, use embedded polished version
  if (!cssContent) {
    cssContent = new Uint8Array(Buffer.from(getEmbeddedMarkdownCss(), "utf8"));
  }

  try {
    // Ensure .vscode folder exists
    try {
      await vscode.workspace.fs.createDirectory(vscodeFolder);
    } catch {
      // Folder may already exist
    }

    await vscode.workspace.fs.writeFile(targetCssUri, cssContent);
    return true;
  } catch (error) {
    console.error("Failed to copy markdown CSS to workspace:", error);
    return false;
  }
}

function getEmbeddedMarkdownCss(): string {
  return `/* GitHub-flavored Markdown Preview Theme */
/* Generated by Alex Environment Setup - Polished Edition */
:root, body, .vscode-body {
    --vscode-textBlockQuote-background: #f6f8fa !important;
    --vscode-textBlockQuote-border: #d1d9e0 !important;
    --vscode-editor-background: #ffffff !important;
    --vscode-editor-foreground: #1f2328 !important;
}
body {
    background-color: #ffffff !important;
    color: #1f2328 !important;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif !important;
    font-size: 16px !important;
    line-height: 1.6 !important;
    max-width: 980px !important;
    margin: 0 auto !important;
    padding: 32px 45px !important;
    word-wrap: break-word !important;
}
h1, h2, h3, h4, h5, h6 {
    color: #1f2328 !important;
    font-weight: 600 !important;
    margin-top: 24px !important;
    margin-bottom: 16px !important;
    line-height: 1.25 !important;
}
h1 { font-size: 2em !important; }
h2 { font-size: 1.5em !important; }
h3 { font-size: 1.25em !important; }
h4 { font-size: 1em !important; }
h1, h2 { border-bottom: 1px solid #d1d9e0 !important; padding-bottom: 0.3em !important; }
a { color: #0969da !important; text-decoration: none !important; }
a:hover { text-decoration: underline !important; }
code {
    background-color: #eff1f3 !important;
    color: #1f2328 !important;
    padding: 0.2em 0.4em !important;
    border-radius: 6px !important;
    font-size: 85% !important;
    font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace !important;
}
pre {
    background-color: #f6f8fa !important;
    border: 1px solid #d1d9e0 !important;
    border-radius: 6px !important;
    padding: 16px !important;
    overflow: auto !important;
    font-size: 85% !important;
    line-height: 1.45 !important;
}
pre code { background-color: transparent !important; padding: 0 !important; border-radius: 0 !important; color: #1f2328 !important; }
pre code, pre code span, pre code * { color: #1f2328 !important; }
pre code .hljs-keyword, pre code .token.keyword { color: #cf222e !important; }
pre code .hljs-string, pre code .token.string { color: #0a3069 !important; }
pre code .hljs-comment, pre code .token.comment { color: #57606a !important; font-style: italic !important; }
pre code .hljs-function, pre code .token.function { color: #8250df !important; }
pre code .hljs-number, pre code .token.number { color: #0550ae !important; }
pre code .hljs-class-name, pre code .token.class-name { color: #953800 !important; }
blockquote {
    border-left: 4px solid #d1d9e0 !important;
    color: #1f2328 !important;
    margin: 0 0 16px 0 !important;
    padding: 8px 16px !important;
    background-color: #f6f8fa !important;
}
blockquote p { margin: 0 !important; }
table { border-collapse: collapse !important; width: 100% !important; margin-bottom: 16px !important; }
th, td { border: 1px solid #d1d9e0 !important; padding: 8px 13px !important; }
th { background-color: #f6f8fa !important; font-weight: 600 !important; }
tr:nth-child(even) { background-color: #f6f8fa !important; }
ul, ol { padding-left: 2em !important; margin-bottom: 16px !important; }
li + li { margin-top: 0.25em !important; }
li input[type="checkbox"] { margin-right: 0.5em !important; }
hr { background-color: #d1d9e0 !important; border: 0 !important; height: 0.25em !important; margin: 24px 0 !important; }
img { max-width: 100% !important; border-radius: 6px !important; }
.mermaid, .mermaid svg { background-color: #ffffff !important; padding: 16px !important; border-radius: 6px !important; text-align: center !important; }
.mermaid rect, .mermaid polygon { fill: #f6f8fa !important; stroke: #d1d9e0 !important; }
.mermaid text, .mermaid tspan { fill: #1f2328 !important; color: #1f2328 !important; }
.mermaid .edgePath path { stroke: #656d76 !important; }
`;
}

/**
 * Apply markdown styles as a workspace setting with relative path
 * 
 * VS Code security prevents loading CSS from arbitrary paths (like ~/.alex/).
 * Instead, we copy the CSS to .vscode/ and use a workspace-relative path.
 */
export async function applyMarkdownStyles(): Promise<boolean> {
  // Copy CSS to workspace .vscode folder
  const copied = await copyMarkdownCssToWorkspace();
  if (!copied) {
    return false;
  }
  
  // Set markdown.styles as a WORKSPACE setting with relative path
  // The relative path ".vscode/markdown-light.css" works within the workspace
  const config = vscode.workspace.getConfiguration();
  const currentValue = config.inspect("markdown.styles");
  
  const relativePath = ".vscode/markdown-light.css";
  
  // Check if already set correctly in workspace settings
  const workspaceArray = currentValue?.workspaceValue as string[] | undefined;
  if (workspaceArray?.includes(relativePath)) {
    return true; // Already correctly configured
  }

  try {
    await config.update(
      "markdown.styles",
      [relativePath],
      vscode.ConfigurationTarget.Workspace
    );
    return true;
  } catch (error) {
    console.error("Failed to set markdown.styles:", error);
    return false;
  }
}
