import * as vscode from "vscode";
import * as path from "path";
import * as os from "os";

/**
 * Get the global Alex directory path (~/.alex)
 */
function getGlobalAlexDir(): string {
  return path.join(os.homedir(), ".alex");
}

/**
 * Essential settings required for Alex to function properly
 */
const ESSENTIAL_SETTINGS: Record<string, unknown> = {
  "chat.instructionsFilesLocations": {
    ".github/instructions": true,
  },
  "chat.useAgentSkills": true,
  "chat.useNestedAgentsMdFiles": true,
  "github.copilot.chat.tools.memory.enabled": true,
};

/**
 * Recommended settings that improve the Alex experience
 */
const RECOMMENDED_SETTINGS: Record<string, unknown> = {
  "github.copilot.chat.agent.thinkingTool": true,
  "chat.agent.maxRequests": 50,
  "chat.experimental.detectParticipant.enabled": true,
  "github.copilot.chat.followUps": "always",
  "chat.agent.todoList": {
    position: "panel",
  },
  // Recommended tools for Alex - these enhance the agent experience
  "chat.tools.enabled": {
    // File and code tools
    "vscode.file_search": true,
    "vscode.grep_search": true,
    "vscode.semantic_search": true,
    "vscode.read_file": true,
    "vscode.replace_string_in_file": true,
    "vscode.multi_replace_string_in_file": true,
    "vscode.create_file": true,
    "vscode.list_dir": true,
    "vscode.list_code_usages": true,
    // Terminal and tasks
    "vscode.run_in_terminal": true,
    "vscode.get_terminal_output": true,
    "vscode.terminal_selection": true,
    "vscode.terminal_last_command": true,
    "vscode.create_and_run_task": true,
    // Development tools
    "vscode.get_errors": true,
    "vscode.get_changed_files": true,
    "vscode.test_failure": true,
    // Web and external
    "vscode.fetch_webpage": true,
    "vscode.open_simple_browser": true,
    // Notebook support
    "vscode.edit_notebook_file": true,
    "vscode.run_notebook_cell": true,
    "vscode.copilot_getNotebookSummary": true,
    // Project management
    "vscode.create_new_workspace": true,
    "vscode.manage_todo_list": true,
    "vscode.memory": true,
    // Subagent support
    "vscode.runSubagent": true,
  },
};

/**
 * Nice-to-have settings that reduce friction
 */
const NICE_TO_HAVE_SETTINGS: Record<string, unknown> = {
  "chat.tools.autoRun": true,
  "chat.tools.fileSystem.autoApprove": true,
  "github.copilot.chat.localeOverride": "en",
  "chat.commandCenter.enabled": true,
  // Note: markdown.styles handled separately as workspace setting
};

interface SettingCategory {
  name: string;
  description: string;
  settings: Record<string, unknown>;
  icon: string;
}

const SETTING_CATEGORIES: SettingCategory[] = [
  {
    name: "Essential",
    description: "Required for full Alex functionality",
    settings: ESSENTIAL_SETTINGS,
    icon: "🔴",
  },
  {
    name: "Recommended",
    description: "Improves the Alex experience",
    settings: RECOMMENDED_SETTINGS,
    icon: "🟡",
  },
  {
    name: "Nice-to-Have",
    description: "Quality of life improvements",
    settings: NICE_TO_HAVE_SETTINGS,
    icon: "🟢",
  },
];

/**
 * Check which settings are already configured
 */
function getExistingSettings(settings: Record<string, unknown>): string[] {
  const config = vscode.workspace.getConfiguration();
  const existing: string[] = [];

  for (const key of Object.keys(settings)) {
    const currentValue = config.inspect(key);
    if (currentValue?.globalValue !== undefined) {
      existing.push(key);
    }
  }

  return existing;
}

/**
 * Copy the markdown preview CSS file to the workspace .vscode folder
 */
async function copyMarkdownCssToGlobal(): Promise<string | null> {
  const globalDir = getGlobalAlexDir();
  const targetCssPath = path.join(globalDir, "markdown-light.css");
  const targetUri = vscode.Uri.file(targetCssPath);
  const globalDirUri = vscode.Uri.file(globalDir);

  // Check if file already exists
  try {
    await vscode.workspace.fs.stat(targetUri);
    return targetCssPath; // Already exists
  } catch {
    // File doesn't exist, need to create it
  }

  // Try to find the CSS in the current workspace's Alex .github folder
  const workspaceFolders = vscode.workspace.workspaceFolders;
  let cssContent: Uint8Array | null = null;

  if (workspaceFolders && workspaceFolders.length > 0) {
    const githubSkillCss = vscode.Uri.joinPath(
      workspaceFolders[0].uri,
      ".github",
      "skills",
      "markdown-mermaid",
      "markdown-light.css"
    );

    try {
      cssContent = await vscode.workspace.fs.readFile(githubSkillCss);
    } catch {
      // CSS not found in workspace
    }
  }

  // If not found in workspace, use embedded basic version
  if (!cssContent) {
    const basicCss = `/* GitHub-flavored Markdown Preview Theme */
/* Generated by Alex Environment Setup */

body {
    background-color: #ffffff !important;
    color: #1f2328 !important;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif !important;
    font-size: 16px !important;
    line-height: 1.5 !important;
    max-width: 980px !important;
    margin: 0 auto !important;
    padding: 45px !important;
}

h1, h2, h3, h4, h5, h6 {
    color: #1f2328 !important;
    font-weight: 600 !important;
    margin-top: 24px !important;
    margin-bottom: 16px !important;
}

h1, h2 {
    border-bottom: 1px solid #d1d9e0 !important;
    padding-bottom: 0.3em !important;
}

code {
    background-color: rgba(175, 184, 193, 0.2) !important;
    padding: 0.2em 0.4em !important;
    border-radius: 6px !important;
    font-family: ui-monospace, "Cascadia Code", "SF Mono", Menlo, monospace !important;
}

pre {
    background-color: #f6f8fa !important;
    border-radius: 6px !important;
    padding: 16px !important;
    overflow: auto !important;
}

pre code {
    background-color: transparent !important;
    padding: 0 !important;
}

blockquote {
    border-left: 4px solid #d1d9e0 !important;
    color: #656d76 !important;
    padding: 0 1em !important;
    margin: 0 !important;
}

a {
    color: #0969da !important;
    text-decoration: none !important;
}

a:hover {
    text-decoration: underline !important;
}

table {
    border-collapse: collapse !important;
    width: 100% !important;
}

th, td {
    border: 1px solid #d1d9e0 !important;
    padding: 6px 13px !important;
}

th {
    background-color: #f6f8fa !important;
    font-weight: 600 !important;
}

hr {
    border: 0 !important;
    border-top: 1px solid #d1d9e0 !important;
    margin: 24px 0 !important;
}

img {
    max-width: 100% !important;
}
`;
    cssContent = new Uint8Array(Buffer.from(basicCss, "utf8"));
  }

  try {
    // Ensure ~/.alex folder exists
    try {
      await vscode.workspace.fs.createDirectory(globalDirUri);
    } catch {
      // Folder may already exist
    }

    await vscode.workspace.fs.writeFile(targetUri, cssContent);
    return targetCssPath;
  } catch (error) {
    console.error("Failed to copy markdown CSS to global location:", error);
    return null;
  }
}

/**
 * Apply settings to VS Code user configuration
 */
async function applySettings(
  settings: Record<string, unknown>,
): Promise<{ applied: string[]; skipped: string[] }> {
  const config = vscode.workspace.getConfiguration();
  const applied: string[] = [];
  const skipped: string[] = [];

  for (const [key, value] of Object.entries(settings)) {
    try {
      // Check if already set
      const currentValue = config.inspect(key);
      if (currentValue?.globalValue !== undefined) {
        skipped.push(key);
        continue;
      }

      await config.update(key, value, vscode.ConfigurationTarget.Global);
      applied.push(key);
    } catch (error) {
      console.error(`Failed to apply setting ${key}:`, error);
      skipped.push(key);
    }
  }

  return { applied, skipped };
}

/**
 * Apply markdown styles as a global setting with absolute path
 * Copies CSS to ~/.alex/ and sets markdown.styles globally
 */
async function applyMarkdownStyles(): Promise<boolean> {
  // Copy CSS to global location (~/.alex/markdown-light.css)
  const cssPath = await copyMarkdownCssToGlobal();
  if (!cssPath) {
    console.error("Failed to copy markdown CSS to global location");
    return false;
  }

  // Set markdown.styles as a GLOBAL setting with absolute path
  const config = vscode.workspace.getConfiguration();
  const currentValue = config.inspect("markdown.styles");
  
  // Skip if already set globally
  if (currentValue?.globalValue !== undefined) {
    return true;
  }

  try {
    await config.update(
      "markdown.styles",
      [cssPath],
      vscode.ConfigurationTarget.Global
    );
    return true;
  } catch (error) {
    console.error("Failed to set markdown.styles:", error);
    return false;
  }
}

/**
 * Format settings as JSON for preview
 */
function formatSettingsPreview(settings: Record<string, unknown>): string {
  return JSON.stringify(settings, null, 2);
}

/**
 * Main command: Setup Alex Environment
 */
export async function setupEnvironment(): Promise<void> {
  // Check what's already configured
  const essentialExisting = getExistingSettings(ESSENTIAL_SETTINGS);
  const recommendedExisting = getExistingSettings(RECOMMENDED_SETTINGS);
  const niceToHaveExisting = getExistingSettings(NICE_TO_HAVE_SETTINGS);

  const essentialNeeded =
    Object.keys(ESSENTIAL_SETTINGS).length - essentialExisting.length;
  const recommendedNeeded =
    Object.keys(RECOMMENDED_SETTINGS).length - recommendedExisting.length;
  const niceToHaveNeeded =
    Object.keys(NICE_TO_HAVE_SETTINGS).length - niceToHaveExisting.length;

  // If everything is configured, let user know
  if (
    essentialNeeded === 0 &&
    recommendedNeeded === 0 &&
    niceToHaveNeeded === 0
  ) {
    vscode.window
      .showInformationMessage(
        "✅ Your VS Code environment is already optimized for Alex!",
        "View Current Settings",
      )
      .then((choice) => {
        if (choice === "View Current Settings") {
          vscode.commands.executeCommand("workbench.action.openSettingsJson");
        }
      });
    return;
  }

  // Build quick pick items
  interface CategoryQuickPickItem extends vscode.QuickPickItem {
    category: SettingCategory;
    needed: number;
    existing: number;
  }

  const items: CategoryQuickPickItem[] = [];

  if (essentialNeeded > 0) {
    items.push({
      label: `${SETTING_CATEGORIES[0].icon} Essential Settings`,
      description: `${essentialNeeded} settings to add`,
      detail: SETTING_CATEGORIES[0].description,
      category: SETTING_CATEGORIES[0],
      needed: essentialNeeded,
      existing: essentialExisting.length,
      picked: true,
    });
  }

  if (recommendedNeeded > 0) {
    items.push({
      label: `${SETTING_CATEGORIES[1].icon} Recommended Settings`,
      description: `${recommendedNeeded} settings to add`,
      detail: SETTING_CATEGORIES[1].description,
      category: SETTING_CATEGORIES[1],
      needed: recommendedNeeded,
      existing: recommendedExisting.length,
      picked: false,
    });
  }

  if (niceToHaveNeeded > 0) {
    items.push({
      label: `${SETTING_CATEGORIES[2].icon} Nice-to-Have Settings`,
      description: `${niceToHaveNeeded} settings to add`,
      detail: SETTING_CATEGORIES[2].description,
      category: SETTING_CATEGORIES[2],
      needed: niceToHaveNeeded,
      existing: niceToHaveExisting.length,
      picked: false,
    });
  }

  // Show multi-select quick pick
  const selected = await vscode.window.showQuickPick(items, {
    canPickMany: true,
    placeHolder:
      "Select which settings to add (your existing settings will NOT be modified)",
    title: "Alex Environment Setup",
  });

  if (!selected || selected.length === 0) {
    return;
  }

  // Collect all settings to apply
  const settingsToApply: Record<string, unknown> = {};
  for (const item of selected) {
    Object.assign(settingsToApply, item.category.settings);
  }

  // Show preview and ask for confirmation
  const preview = formatSettingsPreview(settingsToApply);
  const categoryNames = selected.map((s) => s.category.name).join(", ");

  const confirm = await vscode.window.showInformationMessage(
    `Add ${Object.keys(settingsToApply).length} settings (${categoryNames})?\n\nThis will only ADD new settings - your existing settings will NOT be changed.`,
    { modal: true, detail: `Settings to add:\n${preview}` },
    "Add Settings",
    "Show Preview",
    "Cancel",
  );

  if (confirm === "Show Preview") {
    // Open a preview document
    const doc = await vscode.workspace.openTextDocument({
      content: `// Settings that will be ADDED to your VS Code configuration\n// Your existing settings will NOT be modified\n\n${preview}`,
      language: "jsonc",
    });
    await vscode.window.showTextDocument(doc, { preview: true });

    // Ask again after preview
    const confirmAfterPreview = await vscode.window.showInformationMessage(
      "Add these settings to your VS Code configuration?",
      "Add Settings",
      "Cancel",
    );

    if (confirmAfterPreview !== "Add Settings") {
      return;
    }
  } else if (confirm !== "Add Settings") {
    return;
  }

  // Apply settings
  const result = await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: "Setting up Alex environment...",
      cancellable: false,
    },
    async () => {
      const settingsResult = await applySettings(settingsToApply);
      // Also apply markdown styles as workspace setting
      await applyMarkdownStyles();
      return settingsResult;
    },
  );

  // Show result
  if (result.applied.length > 0) {
    const message =
      result.skipped.length > 0
        ? `✅ Added ${result.applied.length} settings (${result.skipped.length} already configured)`
        : `✅ Added ${result.applied.length} settings`;

    vscode.window
      .showInformationMessage(message, "View Settings")
      .then((choice) => {
        if (choice === "View Settings") {
          vscode.commands.executeCommand("workbench.action.openSettingsJson");
        }
      });
  } else {
    vscode.window.showInformationMessage(
      "All selected settings were already configured.",
    );
  }
}

/**
 * Quick setup that applies essential settings with minimal prompts
 * Used during initialization/upgrade flow
 */
export async function offerEnvironmentSetup(): Promise<boolean> {
  const essentialExisting = getExistingSettings(ESSENTIAL_SETTINGS);
  const essentialNeeded =
    Object.keys(ESSENTIAL_SETTINGS).length - essentialExisting.length;

  // If essential settings are already configured, skip
  if (essentialNeeded === 0) {
    return false;
  }

  const choice = await vscode.window.showInformationMessage(
    `Would you like to optimize VS Code for Alex?\n\nThis adds ${essentialNeeded} essential settings for full Alex functionality.\nYour existing settings will NOT be modified.`,
    "Yes, Add Settings",
    "Show Details",
    "Skip",
  );

  if (choice === "Show Details") {
    // Run the full setup flow
    await setupEnvironment();
    return true;
  } else if (choice === "Yes, Add Settings") {
    // Quick apply essential only
    const result = await applySettings(ESSENTIAL_SETTINGS);
    // Also apply markdown styles as workspace setting
    await applyMarkdownStyles();
    if (result.applied.length > 0) {
      vscode.window.showInformationMessage(
        `✅ Added ${result.applied.length} essential settings for Alex`,
      );
    }
    return true;
  }

  return false;
}
