/**
 * Upgrade Migration — Migration candidates document generation and migration execution
 *
 * Extracted from upgrade.ts for maintainability.
 * Handles: MIGRATION-CANDIDATES.md generation, completeMigration command, showMigrationCandidates command.
 */

import * as vscode from "vscode";
import * as fs from "fs-extra";
import * as path from "path";
import { getAlexWorkspaceFolder } from "../shared/utils";
import { normalizeAllSynapses } from "./upgradeSynapseNormalization";
import type { MigrationCandidate, LegacyDetection } from "./upgrade";

/**
 * Generate the MIGRATION-CANDIDATES.md document
 */
export async function generateMigrationCandidates(
  rootPath: string,
  backupPath: string,
  candidates: MigrationCandidate[],
  detection: LegacyDetection,
  newVersion: string,
): Promise<string> {
  const timestamp = new Date().toISOString().split("T")[0];
  const relativeBackupPath = path
    .relative(rootPath, backupPath)
    .replace(/\\/g, "/");

  let content = `# Migration Candidates

> Generated by Alex Upgrade on ${timestamp}
> Review and check items you want to migrate from your previous installation.
>
> **Previous version:** ${detection.installedVersion || "unknown"} (${detection.version} structure)
> **New version:** ${newVersion}

## Instructions

1. Review each section below
2. Check the boxes \`[x]\` for items you want to keep
3. Run **"Alex: Complete Migration"** when ready
4. Or manually copy files from \`${relativeBackupPath}/\`

---

`;

  // Group candidates by type
  const legacyDK = candidates.filter((c) => c.type === "legacy-dk");
  const userDK = candidates.filter((c) => c.type === "user-dk");
  const userSkills = candidates.filter((c) => c.type === "user-skill");
  const profiles = candidates.filter((c) => c.type === "profile");
  const episodic = candidates.filter((c) => c.type === "episodic");

  // Legacy DK section
  if (legacyDK.length > 0) {
    content += `## 🏛️ Legacy Domain Knowledge (from project root)

These DK files were in your project root. They can be converted to skills:

`;
    for (const c of legacyDK) {
      const staleWarning = c.stale ? " ⚠️ Stale (>90 days)" : "";
      const checked = c.recommended && !c.stale ? "x" : " ";
      content += `- [${checked}] \`${c.sourcePath}\` → \`${c.targetPath}\`${staleWarning}\n`;
      content += `  - ${c.description} (${c.sizeKB} KB)\n\n`;
    }
  }

  // User DK section
  if (userDK.length > 0) {
    content += `## 📚 Domain Knowledge Files

These DK files can be converted to skills:

`;
    for (const c of userDK) {
      const staleWarning = c.stale ? " ⚠️ Stale (>90 days)" : "";
      const checked = c.recommended && !c.stale ? "x" : " ";
      content += `- [${checked}] \`${c.sourcePath}\` → \`${c.targetPath}\`${staleWarning}\n`;
      content += `  - ${c.description} (${c.sizeKB} KB)\n\n`;
    }
  }

  // User Skills section
  if (userSkills.length > 0) {
    content += `## 🎓 User-Created Skills

These skills were created by you and don't exist in the new version:

`;
    for (const c of userSkills) {
      const staleWarning = c.stale ? " ⚠️ Stale (>90 days)" : "";
      const checked = c.recommended && !c.stale ? "x" : " ";
      content += `- [${checked}] \`${c.sourcePath}/\`${staleWarning}\n`;
      content += `  - ${c.description} (${c.sizeKB} KB)\n\n`;
    }
  }

  // Profile section
  if (profiles.length > 0) {
    content += `## 👤 User Profile

Your personal settings and preferences:

`;
    for (const c of profiles) {
      content += `- [x] \`${c.sourcePath}\` — ${c.description}\n`;
    }
    content += "\n";
  }

  // Episodic section
  if (episodic.length > 0) {
    content += `## 📜 Session History

Your meditation sessions, dream reports, and other episodic records:

`;
    for (const c of episodic) {
      content += `- [x] \`${c.sourcePath}/\` — ${c.description} (${c.sizeKB} KB)\n`;
    }
    content += "\n";
  }

  // Backup location
  content += `---

## Backup Location

All original files available at:
\`${relativeBackupPath}/\`

You can manually copy any files from this location.

## Need Help?

Ask Alex: "Help me migrate my previous settings"
`;

  const candidatesPath = path.join(
    rootPath,
    ".github",
    "MIGRATION-CANDIDATES.md",
  );
  await fs.writeFile(candidatesPath, content, "utf8");

  return candidatesPath;
}

/**
 * Execute migration for each checked item from backup to workspace
 */
async function executeMigrationItems(
  checkedItems: string[],
  backupPath: string,
  rootPath: string,
  progress: vscode.Progress<{ message?: string }>,
): Promise<{ migrated: string[]; errors: string[] }> {
  const migrated: string[] = [];
  const errors: string[] = [];

  for (const item of checkedItems) {
    progress.report({ message: path.basename(item) });

    try {
      const arrowMatch = item.match(/^(.+?)\s*→\s*(.+)$/);
      let src: string;
      let dest: string;

      if (arrowMatch) {
        src = path.join(backupPath, arrowMatch[1].trim());
        dest = path.join(rootPath, arrowMatch[2].trim());
      } else {
        src = path.join(backupPath, item);
        dest = path.join(rootPath, item);
      }

      if (await fs.pathExists(src)) {
        await fs.ensureDir(path.dirname(dest));
        await fs.copy(src, dest, { overwrite: true });

        // For DK → skill migration, create a minimal synapses.json if it doesn't exist
        if (
          arrowMatch &&
          dest.endsWith("SKILL.md") &&
          dest.replace(/\\/g, "/").includes(".github/skills/")
        ) {
          const skillDir = path.dirname(dest);
          const synapsesPath = path.join(skillDir, "synapses.json");
          if (!(await fs.pathExists(synapsesPath))) {
            const skillName = path.basename(skillDir);
            const minimalSynapses = {
              $schema: "../SYNAPSE-SCHEMA.json",
              skillId: skillName,
              version: "1.0.0",
              lastUpdated: new Date().toISOString().split("T")[0],
              connections: [],
              activationContexts: [],
              notes: `Migrated from DK file: ${path.basename(arrowMatch[1].trim())}`,
            };
            await fs.writeJson(synapsesPath, minimalSynapses, { spaces: 2 });
          }
        }

        migrated.push(item);
      } else {
        errors.push(`Not found: ${item}`);
      }
    } catch (err: unknown) {
      errors.push(
        `${item}: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  // Normalize synapses for all migrated skills
  progress.report({ message: "Normalizing synapses..." });
  const skillsDir = path.join(rootPath, ".github", "skills");
  if (await fs.pathExists(skillsDir)) {
    const synapseResult = await normalizeAllSynapses(skillsDir);
    if (synapseResult.normalized > 0) {
      migrated.push(`(${synapseResult.normalized} synapse files normalized)`);
    }
  }

  return { migrated, errors };
}

/**
 * Process checked items from MIGRATION-CANDIDATES.md
 */
export async function completeMigration(
  _context: vscode.ExtensionContext,
): Promise<void> {
  const workspaceResult = await getAlexWorkspaceFolder(true);
  if (!workspaceResult.found) {
    vscode.window.showErrorMessage("No workspace with Alex found.");
    return;
  }

  const rootPath = workspaceResult.rootPath!;
  const candidatesPath = path.join(
    rootPath,
    ".github",
    "MIGRATION-CANDIDATES.md",
  );

  if (!(await fs.pathExists(candidatesPath))) {
    vscode.window.showInformationMessage(
      "No migration candidates found. Run 'Alex: Upgrade' first if you need to migrate.",
      "OK",
    );
    return;
  }

  const content = await fs.readFile(candidatesPath, "utf8");

  // Parse checked items: - [x] `path`
  const checkedPattern = /- \[x\] `([^`]+)`/gi;
  const checkedItems: string[] = [];
  let match;
  while ((match = checkedPattern.exec(content)) !== null) {
    checkedItems.push(match[1]);
  }

  if (checkedItems.length === 0) {
    const result = await vscode.window.showInformationMessage(
      "No items are checked for migration.\n\n" +
        "Edit MIGRATION-CANDIDATES.md and check [x] the items you want to keep, then run this command again.",
      "Open Migration Guide",
      "Delete Migration Guide",
      "Cancel",
    );
    if (result === "Open Migration Guide") {
      const doc = await vscode.workspace.openTextDocument(candidatesPath);
      await vscode.window.showTextDocument(doc);
    } else if (result === "Delete Migration Guide") {
      await fs.remove(candidatesPath);
      vscode.window.showInformationMessage("Migration guide deleted.");
    }
    return;
  }

  // Find backup path from the document
  const backupMatch = content.match(/`(archive\/upgrades\/backup-[^`]+)`/);
  if (!backupMatch) {
    vscode.window.showErrorMessage(
      "Could not find backup path in migration document.",
    );
    return;
  }

  const backupPath = path.join(rootPath, backupMatch[1]);
  if (!(await fs.pathExists(backupPath))) {
    vscode.window.showErrorMessage(`Backup not found: ${backupMatch[1]}`);
    return;
  }

  const confirm = await vscode.window.showInformationMessage(
    `Migrate ${checkedItems.length} item(s)?`,
    { modal: true },
    "Yes, Migrate",
    "Cancel",
  );
  if (confirm !== "Yes, Migrate") {
    return;
  }

  // Execute migration
  const { migrated, errors } = await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: "Migrating...",
      cancellable: false,
    },
    async (progress) =>
      executeMigrationItems(checkedItems, backupPath, rootPath, progress),
  );

  await fs.remove(candidatesPath);

  // Show results
  let message = `✅ Migration complete!\n\nMigrated: ${migrated.length} item(s)`;
  if (errors.length > 0) {
    message += `\n⚠️ Errors: ${errors.length}`;
  }

  const result = await vscode.window.showInformationMessage(
    message,
    "Run Dream Check",
    "OK",
  );
  if (result === "Run Dream Check") {
    await vscode.commands.executeCommand("alex.dream");
  }
}

/**
 * Show migration candidates document
 */
export async function showMigrationCandidates(): Promise<void> {
  const workspaceResult = await getAlexWorkspaceFolder(true);
  if (!workspaceResult.found) {
    vscode.window.showErrorMessage("No workspace with Alex found.");
    return;
  }

  const candidatesPath = path.join(
    workspaceResult.rootPath!,
    ".github",
    "MIGRATION-CANDIDATES.md",
  );

  if (!(await fs.pathExists(candidatesPath))) {
    vscode.window.showInformationMessage(
      "No migration candidates found. Run 'Alex: Upgrade' first if you need to migrate.",
    );
    return;
  }

  const doc = await vscode.workspace.openTextDocument(candidatesPath);
  await vscode.window.showTextDocument(doc);
}
